---

vpn_redhat_name: 'Red Hat AMS2'
vpn_redhat_cert: 'RH-IT-Root-CA.crt'
vpn_redhat_gateway: 'ovpn-ams2.redhat.com'
vpn_redhat_user: 'YOUR USER HERE'
vpn_redhat_path: '/etc/NetworkManager/system-connections'

vpn_rpms: ['NetworkManager-libreswan', 'NetworkManager-libreswan-gnome', 'NetworkManager-openconnect',  'NetworkManager-openconnect-gnome', 'openconnect',  'openvpn', 'vpnc-script', 'NetworkManager-fortisslvpn', 'NetworkManager-fortisslvpn-gnome', 'openfortivpn', 'NetworkManager-l2tp', 'NetworkManager-l2tp-gnome', 'NetworkManager-pptp', 'NetworkManager-pptp-gnome', 'NetworkManager-openvpn', 'NetworkManager-openvpn-gnome']
